s1=set(input("Enter the first set: ").split())
s2=set(input("Enter the second set: ").split())
u=s1.union(s2)
i=s1.intersection(s2)
s=s1.symmetric_difference(s2)
d=s1.difference(s2)
dis=s1.isdisjoint(s2)
sub=s1.issubset(s2)
super=s1.issuperset(s2)

print("Union: ",u)
print("Intersection: ",i)
print("Symmetric Difference: ",s)
print("Difference: ",d)
print("Is Disjoint: ",dis)
print("Is Subset: ",sub)
print("Is Superset: ",super)
